### ISSUE TITLE
Pairing problem 

### ISSUE THREAD

**Issue by BorussiaPlayer17** [twocolors/node-red-contrib-apple-tv-x#5]
Hey,

I’m using node red official docker image. When I try to pair my Apple TV 4K I’m getting just an error “ No devices retrieved, check your Apple TVs connection settings”. ATV is Running. I have no clue how to debug that. 

Greetings

**Comment by twocolors** [comment]
oh, check mdns in docker

**Comment by BorussiaPlayer17** [comment]
mDNS just works in the same subnet. As docker creates his own subnet the Plugin can't detect the AppleTV. Running the container in "network_mode: host" solves this issue. 

Thank you for your hint!

**Comment by twocolors** [comment]
i use

```
  node-red:
#    image: nrchkb/node-red-homekit:latest-12-minimal
    image: nrchkb/node-red-homekit:latest-14-minimal
    hostname: kubik3
    container_name: node-red
    environment:
      - TZ=Europe/Moscow
      - PORT=80
    networks:
      bridge:
      local:
        ipv4_address: 192.168.0.11
    volumes:
      - /home/pi/.node-red:/data
    restart: unless-stopped

networks:
  local:
    external: true
  bridge:
    driver: bridge
```
and
```
pi@holyland:~ $ docker network ls
NETWORK ID     NAME        DRIVER    SCOPE
9c4c28970f73   local       macvlan   local
```
in macvlan full work mDNS in docker and host machins
